"""Add Image table

Revision ID: 64dcf565bb39
Revises: 86b74cc3f788
Create Date: 2024-11-24 13:48:08.618037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64dcf565bb39'
down_revision: Union[str, None] = '86b74cc3f788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('image_path')
    )
    op.create_index(op.f('ix_images_image_path'), 'images', ['image_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_path'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
